Data Source : NCBI Database
Organism- Homo Sapiens
Gene Name- Homo sapiens voucher BM141 cytochrome c oxidase subunit I (COX1) gene, partial cds; mitochondrial
Accession-PZ148508

# DNA Sequence Length

dna_seq="CAAAGACATTGGCACACTATACCTATTATTCGGCGCATGAGCTGGAGTCCTAGGCACAGCTCTAAGCCTCCTTATTCGAGCCGAGCTGGGCCAGCCAGGCAACCTTCTAGGTAACGACCACATCTACAACGTTATCGTCACAGCCCATGCATTTGTAATAATCTTCTTCATAGTAATACCCATCATAATCGGAGGCTTTGGCAACTGACTAGTTCCCCTAATAATCGGTGCCCCCGATATGGCGTTTCCCCGCATAAACAACATAAGCTTCTGACTCTTACCTCCCTCTCTCCTACTCCTGCTCGCATCTGCTATAGTGGAGGCCGGAGCAGGAACAGGTTGAACAATCTACCCTCCCTTAGCAGGGAACTACTCCCACCCTGGAGCCTCCGTAGACCTAACCATCTTCTCCTTACACCTAGCAGGTGTCTCCTCTATCTTAGGGGCCATCAATTTCATCACAACAATTATCAATATAAAACCCCCTGCCATAACCCAATACCAAACGCCCCTCTTCGTCTGATCCGTCCTAATCACAGCAGTCCTACTTCTCCTATCTCTCCCAGTCCTAGCTGCTGGCATCACTATACTACTAACAGACCGCAACCTCAACACCACCTTCTTCGACCCCGCCGGAGGAGGAGACCCCATTCTATACCAACAC"

# Sequence Length

seq_length= len(dna_seq)

# Nucleotide Counts

 A= dna_seq.count("A")
 T= dna_seq.count("T")
 G= dna_seq.count("G")
 C= dna_seq.count("C")

# Percentage of Purine and pyrimidine

 Purines_percent= ((A+G)/seq_length)*100
 Pyrimidine_percent=((C+T)/ seq_length) *100
 
#Calculate GC Content

 gc_content= ((G+C)/seqlength)*100


print("Sequence Length:", seq_length)
print("A:", A)
print("T:", T)
print("G:", G)
print("C:", C)
print("GC Content:", round(gc_content, 2), "%")
print("Purines:", round(Purines_percent, 2), "%")
print("Pyrimidines:", round(Pyrimidine_percent, 2), "%")